### PR TITLE
Updated project to build in VS2015

### PR DESCRIPTION
**Pull request by snoozbuster**
Also, updated the readme with basic build instructions. These changes are overall very minor and shouldn't affect prior versions of VS or versions without Silverlight 4.

### CODE REVIEW

**Comment by snoozbuster** [comment]
Put this on hold, I thought my version was working normally but when trying to view a gif/webm/image I get three dialogs; first a filesize much too large to be the filesize of the image (>45MB), then "An external component has thrown an exception" followed by the stack trace. Some of this might be provided by the debugger, though.

**Comment by snoozbuster** [comment]
Looks like there's some sort of SDK version mismatch in GIFSurface when it attempts to create the D3D11 device. Specifically, "0x887a002d: The application requested an operation that depends on an SDK component that is missing or mismatched." After some research, this is simply be a machine problem in which I have mismatched D3D11 debug libraries. Building and running in Release mode works fine, and if I could find the appropriate set of debug libraries for either my computer or my phone or both this should work fine. This should be fine to merge; in the meantime I'll try to locate a resolution and add it to the readme.

**Comment by snoozbuster** [comment]
This should be okay to go now. I added a constant that can be defined to unconditionally disable D3D debug devices, which is by default undefined. This is a quick and dirty workaround for affected systems that is probably the best we're going to get without knowing how pantaloons has his environment set up.

**Comment by RailsRoyale** [comment]
Sorry for the wait. I'm not very familiar with github so it took me some time to figure out how I was going to get your changes.

It built fine on VS2013 and I was able to use the debug build to go around the app.

I continued to run into the .nuget issue though, so I may send another pull request to simply remove the .nuget folder because it isn't necessary in the first place. You can just get the latest nuget package from VS package manager anyways.

**Comment by snoozbuster** [comment]
I'll just add that to the PR real quick, no reason to make a new one. Glad to see it builds fine on yours!

**Pull request closed without merging**
